/**
 * MP3 Player — Nintendo Switch Homebrew
 * Stack: libnx + SDL2 + SDL2_image + SDL2_mixer + nlohmann/json  (C++17)
 *
 * Theme system
 * ─────────────
 * On startup the app scans  romfs:/themes/  for subdirectories that contain
 * a  theme.json  file (generated by tools/theme_editor/).
 * If none are found it falls back to the built-in "default" palette (no
 * assets required — pure colour rectangles).
 *
 * The theme-selector screen is shown with  Y  from the main screen.
 * Navigate with DPad Up/Down, confirm with A, go back with B.
 */

#include <switch.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_ttf.h>

// Single-header JSON library — copy nlohmann/json.hpp into include/
// https://github.com/nlohmann/json/releases  (single-include header)
#include <nlohmann/json.hpp>
using json = nlohmann::json;

#include <algorithm>
#include <dirent.h>
#include <fstream>
#include <string>
#include <vector>
#include <cstdio>

// ─── Screen constants ────────────────────────────────────────────────────────

static constexpr int SCREEN_W    = 1280;   // Switch portable-mode width  (px)
static constexpr int SCREEN_H    = 720;    // Switch portable-mode height (px)

// ─── Layout constants  (match tools/theme_editor preview exactly) ─────────────

//  Header bar:   x=0    y=0    w=1280  h=60
static constexpr SDL_Rect RECT_HEADER   = {0,   0,   1280, 60};

//  Player panel: x=40   y=70   w=460   h=580
static constexpr SDL_Rect RECT_PLAYER   = {40,  70,  460,  580};

//  Album art:    x=60   y=90   w=420   h=320
static constexpr SDL_Rect RECT_ART      = {60,  90,  420,  320};

//  Track name:   x=60   y=425  w=420   h=36
static constexpr SDL_Rect RECT_TNAME    = {60,  425, 420,  36};

//  Progress bg:  x=60   y=475  w=420   h=10
static constexpr SDL_Rect RECT_PROG_BG  = {60,  475, 420,  10};

//  Btn Prev:     x=80   y=500  w=70    h=70
static constexpr SDL_Rect RECT_BTN_PRV  = {90,  500, 70,   70};

//  Btn Play:     x=195  y=490  w=90    h=90
static constexpr SDL_Rect RECT_BTN_PLY  = {220, 490, 90,   90};

//  Btn Next:     x=350  y=500  w=70    h=70
static constexpr SDL_Rect RECT_BTN_NXT  = {365, 500, 70,   70};

//  Playlist:     x=540  y=70   w=700   h=580
static constexpr SDL_Rect RECT_PLAYLIST = {540, 70,  700,  580};

//  Footer bar:   x=0    y=660  w=1280  h=60
static constexpr SDL_Rect RECT_FOOTER   = {0,   660, 1280, 60};

//  Playlist rows: 50 px tall, up to 10 visible
static constexpr int VISIBLE_ROWS = 10;
static constexpr int ROW_H        = 50;

// Music directory on the SD card
static constexpr const char* MUSIC_DIR    = "sdmc:/Music";
static constexpr const char* THEMES_DIR   = "romfs:/themes";

// Export APIC (Attached Picture) from MP3

// Rutina ultra-ligera para extraer el buffer del frame APIC (ID3v2) de un MP3
static std::vector<uint8_t> extraerBufferPortadaID3(const std::string& rutaMP3) {
    std::vector<uint8_t> bufferImagen;
    FILE* f = fopen(rutaMP3.c_str(), "rb");
    if (!f) return bufferImagen;

    char tag[3];
    if (fread(tag, 1, 3, f) != 3 || tag[0] != 'I' || tag[1] != 'D' || tag[2] != '3') {
        fclose(f);
        return bufferImagen; // No tiene cabecera ID3v2
    }

    // Saltar el resto de la cabecera principal de ID3 (7 bytes)
    fseek(f, 7, SEEK_CUR);

    char frameID[4];
    while (fread(frameID, 1, 4, f) == 4) {
        // Si los bytes del ID son 0, llegamos al final del padding de etiquetas
        if (frameID[0] == 0) break; 

        // Leer tamaño del frame (4 bytes)
        uint8_t sizeBytes[4];
        if (fread(sizeBytes, 1, 4, f) != 4) break;
        uint32_t frameSize = (sizeBytes[0] << 24) | (sizeBytes[1] << 16) | (sizeBytes[2] << 8) | sizeBytes[3];

        // Saltar banderas (2 bytes)
        fseek(f, 2, SEEK_CUR);

        // ¿Es el frame de la portada? (APIC en ID3v2.3/v2.4)
        if (strncmp(frameID, "APIC", 4) == 0) {
            long posicionInicioFrame = ftell(f);

            // El frame APIC tiene: Text encoding (1 byte), MIME type (variable terminada en 0),
            // Picture type (1 byte), Description (variable terminada en 0).
            uint8_t encoding;
            if (fread(&encoding, 1, 1, f) != 1) break;

            // Saltar MIME Type (ej: "image/jpeg")
            while (fgetc(f) > 0);

            // Saltar Picture Type
            fseek(f, 1, SEEK_CUR);

            // Saltar Descripción
            if (encoding == 1 || encoding == 2) { // UTF-16
                uint16_t ch;
                while (fread(&ch, 2, 1, f) == 1 && ch != 0);
            } else { // ASCII / UTF-8
                while (fgetc(f) > 0);
            }

            long posicionInicioDatos = ftell(f);
            uint32_t bytesSaltados = posicionInicioDatos - posicionInicioFrame;
            uint32_t tamanoImagen = frameSize - bytesSaltados;

            // Leer los bytes puros de la imagen (JPEG/PNG)
            bufferImagen.resize(tamanoImagen);
            fread(bufferImagen.data(), 1, tamanoImagen, f);
            break;
        } else {
            // Saltar el contenido de este frame para ir al siguiente
            fseek(f, frameSize, SEEK_CUR);
        }
    }

    fclose(f);
    return bufferImagen;
}

// ─── Colour helpers ──────────────────────────────────────────────────────────

static SDL_Color hexToColor(const std::string& hex, SDL_Color fallback) {
    if (hex.size() == 7 && hex[0] == '#') {
        try {
            uint32_t v = static_cast<uint32_t>(std::stoul(hex.substr(1), nullptr, 16));
            return SDL_Color{
                static_cast<Uint8>((v >> 16) & 0xFF),
                static_cast<Uint8>((v >>  8) & 0xFF),
                static_cast<Uint8>( v        & 0xFF),
                255
            };
        } catch (...) {}
    }
    return fallback;
}

// ─── Theme ───────────────────────────────────────────────────────────────────

struct Theme {
    // ── Colour palette (built-in defaults) ───────────────────────────────
    SDL_Color background    = { 18,  18,  28, 255};
    SDL_Color panelPlayer   = { 32,  32,  50, 255};
    SDL_Color panelPlaylist = { 32,  32,  50, 255};
    SDL_Color header        = { 26,  26,  46, 255};
    SDL_Color footer        = { 26,  26,  46, 255};
    SDL_Color accent        = { 90, 170, 255, 255};
    SDL_Color selectedRow   = { 55,  75, 135, 255};
    SDL_Color nowPlaying    = { 40, 110, 200, 255};
    SDL_Color progressBg    = { 45,  45,  65, 255};
    SDL_Color progressFill  = { 80, 150, 255, 255};
    SDL_Color btnNormal     = { 55,  55,  85, 255};
    SDL_Color btnPrimary    = { 90, 170, 255, 255};
    SDL_Color albumArtBg    = { 55,  75, 135, 255};
    SDL_Color textPrimary   = {255, 255, 255, 255};
    SDL_Color textSecondary = {170, 170, 204, 255};
    SDL_Color textHint      = {102, 102, 136, 255};

    // ── Loaded SDL textures (nullptr = use colour fallback) ───────────────
    SDL_Texture* texBackground    = nullptr;  // 1280×720
    SDL_Texture* texHeader        = nullptr;  // 1280×60
    SDL_Texture* texFooter        = nullptr;  // 1280×60
    SDL_Texture* texPanelPlayer   = nullptr;  // 460×580
    SDL_Texture* texPanelPlaylist = nullptr;  // 700×580
    SDL_Texture* texAlbumArtDef   = nullptr;  // 420×320
    SDL_Texture* texProgressBg    = nullptr;  // 420×10
    SDL_Texture* texProgressFill  = nullptr;  // 1×10  (stretched)
    SDL_Texture* texBtnPlay       = nullptr;  // 90×90
    SDL_Texture* texBtnPause      = nullptr;  // 90×90
    SDL_Texture* texBtnPrev       = nullptr;  // 70×70
    SDL_Texture* texBtnNext       = nullptr;  // 70×70

    std::string displayName = "Default";

    void destroy() {
        auto freeT = [](SDL_Texture*& t){ if(t){SDL_DestroyTexture(t);t=nullptr;} };
        freeT(texBackground); freeT(texHeader);      freeT(texFooter);
        freeT(texPanelPlayer); freeT(texPanelPlaylist);
        freeT(texAlbumArtDef); freeT(texProgressBg); freeT(texProgressFill);
        freeT(texBtnPlay); freeT(texBtnPause); freeT(texBtnPrev); freeT(texBtnNext);
    }
};

static SDL_Texture* loadTex(SDL_Renderer* r, const std::string& path) {
    if (path.empty()) return nullptr;
    return IMG_LoadTexture(r, path.c_str());  // nullptr on failure → colour fallback
}

static Theme loadTheme(SDL_Renderer* renderer, const std::string& themeDir,
                       const std::string& name) {
    Theme t;
    t.displayName = name;

    std::string jsonPath = themeDir + "/theme.json";
    std::ifstream f(jsonPath);
    if (!f.is_open()) return t;

    json j;
    try { f >> j; } catch (...) { return t; }

    auto getCol = [&](const char* key, SDL_Color def) -> SDL_Color {
        try { return hexToColor(j.at("colors").at(key).get<std::string>(), def); }
        catch (...) { return def; }
    };

    t.background    = getCol("background",    t.background);
    t.panelPlayer   = getCol("panel_player",  t.panelPlayer);
    t.panelPlaylist = getCol("panel_playlist",t.panelPlaylist);
    t.header        = getCol("header",        t.header);
    t.footer        = getCol("footer",        t.footer);
    t.accent        = getCol("accent",        t.accent);
    t.selectedRow   = getCol("selected_row",  t.selectedRow);
    t.nowPlaying    = getCol("now_playing",   t.nowPlaying);
    t.progressBg    = getCol("progress_bg",   t.progressBg);
    t.progressFill  = getCol("progress_fill", t.progressFill);
    t.btnNormal     = getCol("btn_normal",    t.btnNormal);
    t.btnPrimary    = getCol("btn_primary",   t.btnPrimary);
    t.albumArtBg    = getCol("album_art_bg",  t.albumArtBg);
    t.textPrimary   = getCol("text_primary",  t.textPrimary);
    t.textSecondary = getCol("text_secondary",t.textSecondary);
    t.textHint      = getCol("text_hint",     t.textHint);

    auto assetPath = [&](const char* key) -> std::string {
        try {
            std::string rel = j.at("assets").at(key).get<std::string>();
            if (rel.empty()) return "";
            return themeDir + "/" + rel;
        } catch (...) { return ""; }
    };

    t.texBackground    = loadTex(renderer, assetPath("background"));
    t.texHeader        = loadTex(renderer, assetPath("header"));
    t.texFooter        = loadTex(renderer, assetPath("footer"));
    t.texPanelPlayer   = loadTex(renderer, assetPath("panel_player"));
    t.texPanelPlaylist = loadTex(renderer, assetPath("panel_playlist"));
    t.texAlbumArtDef   = loadTex(renderer, assetPath("album_art_default"));
    t.texProgressBg    = loadTex(renderer, assetPath("progress_bg"));
    t.texProgressFill  = loadTex(renderer, assetPath("progress_fill"));
    t.texBtnPlay       = loadTex(renderer, assetPath("btn_play"));
    t.texBtnPause      = loadTex(renderer, assetPath("btn_pause"));
    t.texBtnPrev       = loadTex(renderer, assetPath("btn_prev"));
    t.texBtnNext       = loadTex(renderer, assetPath("btn_next"));

    return t;
}

// ─── Theme catalogue ─────────────────────────────────────────────────────────

struct ThemeCatalogue {
    std::vector<std::string> names;   // folder names under romfs:/themes/
    int selected = 0;                 // currently highlighted (0 = built-in)

    void scan() {
        names.clear();
        DIR* dir = opendir(THEMES_DIR);
        if (!dir) return;
        struct dirent* e;
        while ((e = readdir(dir)) != nullptr) {
            if (e->d_type != DT_DIR) continue;
            std::string n = e->d_name;
            if (n == "." || n == "..") continue;
            std::string jsonPath = std::string(THEMES_DIR) + "/" + n + "/theme.json";
            std::ifstream check(jsonPath);
            if (check.is_open()) names.push_back(n);
        }
        closedir(dir);
        std::sort(names.begin(), names.end());
    }
};

// ─── Application state ───────────────────────────────────────────────────────

enum class Screen { Player, ThemeSelector, ExitConfirmation };

struct AppState {
    std::vector<std::string> playlist;
    int  selectedIndex = 0;
    int  playingIndex  = -1;
    bool isPlaying     = false;
    int  scrollOffset  = 0;
    bool isLooping     = true;
    Mix_Music* currentMusic = nullptr;
    SDL_Texture* trackAlbumArt = nullptr;

    Screen         screen = Screen::Player;
    ThemeCatalogue themes;

    Screen         prevScreen = Screen::Player;
};

// ─── Render helpers ──────────────────────────────────────────────────────────

static void fillRect(SDL_Renderer* r, const SDL_Rect& rect, SDL_Color c) {
    SDL_SetRenderDrawColor(r, c.r, c.g, c.b, c.a);
    SDL_RenderFillRect(r, &rect);
}

static void outlineRect(SDL_Renderer* r, const SDL_Rect& rect, SDL_Color c) {
    SDL_SetRenderDrawColor(r, c.r, c.g, c.b, c.a);
    SDL_RenderDrawRect(r, &rect);
}

// Draw texture if available, otherwise solid-colour rectangle
static void drawTexOrColor(SDL_Renderer* r,
                           SDL_Texture* tex, const SDL_Rect& dst,
                           SDL_Color fallback) {
    if (tex) SDL_RenderCopy(r, tex, nullptr, &dst);
    else     fillRect(r, dst, fallback);
}

// Render a UTF-8 string clipped to maxW pixels (0 = no limit).
// Draws left-aligned at (x, y). Returns drawn width.
static int renderText(SDL_Renderer* r, TTF_Font* font,
                      const std::string& text, int x, int y,
                      SDL_Color color, int maxW = 0) {
    if (!font || text.empty()) return 0;
    SDL_Surface* surf = TTF_RenderUTF8_Blended(font, text.c_str(), color);
    if (!surf) return 0;
    int w = surf->w, h = surf->h;
    if (maxW > 0 && w > maxW) w = maxW;
    SDL_Texture* tex = SDL_CreateTextureFromSurface(r, surf);
    SDL_FreeSurface(surf);
    if (!tex) return 0;
    const SDL_Rect src = {0, 0, w, h};
    const SDL_Rect dst = {x, y, w, h};
    SDL_RenderCopy(r, tex, &src, &dst);
    SDL_DestroyTexture(tex);
    return w;
}

// Render text centred horizontally within a rect
static void renderTextCentered(SDL_Renderer* r, TTF_Font* font,
                                const std::string& text,
                                const SDL_Rect& bounds, SDL_Color color) {
    if (!font || text.empty()) return;
    int tw, th;
    TTF_SizeUTF8(font, text.c_str(), &tw, &th);
    int x = bounds.x + (bounds.w - tw) / 2;
    int y = bounds.y + (bounds.h - th) / 2;
    renderText(r, font, text, x, y, color);
}

// Strip the ".mp3" / ".MP3" extension for display
static std::string trackDisplayName(const std::string& filename) {
    if (filename.size() > 4) {
        std::string ext = filename.substr(filename.size() - 4);
        std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
        if (ext == ".mp3") return filename.substr(0, filename.size() - 4);
    }
    return filename;
}

// ─── File scanning ───────────────────────────────────────────────────────────

static bool hasMP3Ext(const std::string& name) {
    if (name.size() < 4) return false;
    std::string ext = name.substr(name.size() - 4);
    std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
    return ext == ".mp3" && name[0] != '.';  // ignore hidden files
}

static void scanMusicDir(AppState& s) {
    s.playlist.clear();
    DIR* dir = opendir(MUSIC_DIR);
    if (!dir) return;
    struct dirent* e;
    while ((e = readdir(dir)) != nullptr) {
        std::string n = e->d_name;
        if (hasMP3Ext(n)) s.playlist.push_back(n);
    }
    closedir(dir);
    std::sort(s.playlist.begin(), s.playlist.end());
}

// ─── Audio ───────────────────────────────────────────────────────────────────

static void stopAudio(AppState& s) {
    if (s.currentMusic) { Mix_HaltMusic(); Mix_FreeMusic(s.currentMusic); s.currentMusic = nullptr; }
    // Libera la textura de la carátula de la canción anterior si existe
    if (s.trackAlbumArt) { 
        SDL_DestroyTexture(s.trackAlbumArt); 
        s.trackAlbumArt = nullptr; 
    }
    s.isPlaying = false; s.playingIndex = -1;
}

static void playTrack(AppState& s, SDL_Renderer* r, int idx) {
    if (idx < 0 || idx >= (int)s.playlist.size()) return;
    stopAudio(s); // Limpia la música y carátulas anteriores

    // 1. Reconstruir la ruta completa al archivo (Esto es lo que le faltaba a la línea 420)
    std::string path = std::string(MUSIC_DIR) + "/" + s.playlist[idx];
    
    // 2. Cargar el archivo de música
    s.currentMusic = Mix_LoadMUS(path.c_str());

    if (s.currentMusic) {
        Mix_PlayMusic(s.currentMusic, 1);
        s.playingIndex = idx;
        s.isPlaying = true;

        // 3. Extraer y cargar la portada desde el binario del MP3 usando 'path'
        std::vector<uint8_t> bytesImagen = extraerBufferPortadaID3(path);
        
        if (!bytesImagen.empty()) {
            SDL_RWops* rw = SDL_RWFromMem(bytesImagen.data(), bytesImagen.size());
            if (rw) {
                SDL_Surface* tempSurface = IMG_Load_RW(rw, 1);
                if (tempSurface) {
                    s.trackAlbumArt = SDL_CreateTextureFromSurface(r, tempSurface);
                    SDL_FreeSurface(tempSurface);
                    
                    if (s.trackAlbumArt) {
                        SDL_SetTextureBlendMode(s.trackAlbumArt, SDL_BLENDMODE_BLEND);
                    }
                }
            }
        }
    }
}

static void togglePause(AppState& s) {
    if (!s.isPlaying) return;
    if (Mix_PausedMusic()) Mix_ResumeMusic(); else Mix_PauseMusic();
}

static void toggleLoop(AppState& s) {
    s.isLooping = !s.isLooping;
}

static void clampScroll(AppState& s) {
    if (s.selectedIndex < s.scrollOffset)
        s.scrollOffset = s.selectedIndex;
    if (s.selectedIndex >= s.scrollOffset + VISIBLE_ROWS)
        s.scrollOffset = s.selectedIndex - VISIBLE_ROWS + 1;
}

// ─── Rendering — Player screen ───────────────────────────────────────────────

static void renderPlayer(SDL_Renderer* r, TTF_Font* fntBig, TTF_Font* fntMed,
                         TTF_Font* fntSmall, const AppState& s, const Theme& th) {

    // Full-screen background  1280×720
    const SDL_Rect fullScreen = {0, 0, SCREEN_W, SCREEN_H};
    drawTexOrColor(r, th.texBackground, fullScreen, th.background);

    // Header bar  1280×60
    drawTexOrColor(r, th.texHeader, RECT_HEADER, th.header);

    // Player panel  460×580  (left card)
    drawTexOrColor(r, th.texPanelPlayer, RECT_PLAYER, th.panelPlayer);
    if (!th.texPanelPlayer) outlineRect(r, RECT_PLAYER, th.accent);

    //   Album art  420×320
    drawTexOrColor(r, th.texAlbumArtDef, RECT_ART, th.albumArtBg);
    if (!th.texAlbumArtDef) outlineRect(r, RECT_ART, th.accent);

    //   Track name area  420×36
    fillRect(r, RECT_TNAME, th.btnNormal);
    {
        std::string tname = (s.playingIndex >= 0)
            ? trackDisplayName(s.playlist[s.playingIndex])
            : "No track playing";
        int ty = RECT_TNAME.y + (RECT_TNAME.h - TTF_FontHeight(fntMed)) / 2;
        renderText(r, fntMed, tname, RECT_TNAME.x + 6, ty, th.textPrimary,
                   RECT_TNAME.w - 12);
    }

    //   Progress bar track  420×10
    drawTexOrColor(r, th.texProgressBg, RECT_PROG_BG, th.progressBg);
    if (s.isPlaying) {
        // Replace 140 with  (int)(ratio * 420)  when duration is known
        const SDL_Rect fill = {RECT_PROG_BG.x, RECT_PROG_BG.y, 140, RECT_PROG_BG.h};
        drawTexOrColor(r, th.texProgressFill, fill, th.progressFill);
    }

    //   Btn Prev  70×70
    drawTexOrColor(r, th.texBtnPrev, RECT_BTN_PRV, th.btnNormal);
    if (!th.texBtnPrev) outlineRect(r, RECT_BTN_PRV, th.accent);

    //   Btn Play/Pause  90×90
    SDL_Texture* playTex = s.isPlaying ? th.texBtnPause : th.texBtnPlay;
    SDL_Color    playCl  = s.isPlaying ? th.btnPrimary  : th.btnNormal;
    drawTexOrColor(r, playTex, RECT_BTN_PLY, playCl);
    if (!playTex) outlineRect(r, RECT_BTN_PLY, th.accent);

    //   Btn Next  70×70
    drawTexOrColor(r, th.texBtnNext, RECT_BTN_NXT, th.btnNormal);
    if (!th.texBtnNext) outlineRect(r, RECT_BTN_NXT, th.accent);

    // draw loop playlist
    if (s.isLooping) {
        const SDL_Rect loopRect = {315, 620, 190, 30};
        fillRect(r, loopRect, th.btnPrimary);
        renderTextCentered(r, fntSmall, "PLAYLIST LOOP", loopRect, th.textPrimary);
    }else{
        const SDL_Rect loopRect = {315, 620, 190, 30};
        fillRect(r, loopRect, th.btnNormal);
        renderTextCentered(r, fntSmall, "PLAYLIST LOOP", loopRect, th.textHint);
    }

    // Playlist panel  700×580  (right card)
    drawTexOrColor(r, th.texPanelPlaylist, RECT_PLAYLIST, th.panelPlaylist);
    if (!th.texPanelPlaylist) outlineRect(r, RECT_PLAYLIST, th.accent);

    // Header title with 
    renderTextCentered(r, fntBig, "MPlayer 0.01", RECT_HEADER, th.textPrimary);

    if (s.playlist.empty()) {
        const SDL_Rect emptyRow = {560, 90, 660, ROW_H};
        fillRect(r, emptyRow, th.btnNormal);
        renderTextCentered(r, fntSmall, "No MP3 files in sdmc:/Music", emptyRow,
                           th.textSecondary);
    } else {
        for (int i = 0; i < VISIBLE_ROWS; ++i) {
            int idx = i + s.scrollOffset;
            if (idx >= (int)s.playlist.size()) break;
            int rowY = RECT_PLAYLIST.y + i * ROW_H;
            const SDL_Rect row = {RECT_PLAYLIST.x + 2, rowY, RECT_PLAYLIST.w - 4, ROW_H - 2};
            if (idx == s.selectedIndex) fillRect(r,   row, th.selectedRow);
            if (idx == s.playingIndex)  outlineRect(r, row, th.nowPlaying);
            SDL_Color tc = th.textPrimary;
            int ty = rowY + (ROW_H - TTF_FontHeight(fntSmall)) / 2;
            std::string trackConNumero = std::to_string(idx + 1) + ". " + trackDisplayName(s.playlist[idx]);
            renderText(r, fntSmall, trackConNumero,
                       RECT_PLAYLIST.x + 10, ty, tc, RECT_PLAYLIST.w - 20);
        }
    }

    // Footer bar  1280×60 with text aligned to left
    drawTexOrColor(r, th.texFooter, RECT_FOOTER, th.footer);
    renderText(r, fntSmall,
               "A Play | B Pause | ZL/ZR Prev/Next | R Loop | Y Themes | + Exit",
               RECT_FOOTER.x + 10, RECT_FOOTER.y + (RECT_FOOTER.h - TTF_FontHeight(fntSmall)) / 2,
               th.textHint, RECT_FOOTER.w - 20);
}

// ─── Rendering — Theme selector screen ───────────────────────────────────────

static void renderThemeSelector(SDL_Renderer* r, TTF_Font* fntBig, TTF_Font* fntMed,
                                TTF_Font* fntSmall, const AppState& s, const Theme& th) {

    // Background (reuse current theme colours)
    const SDL_Rect full = {0, 0, SCREEN_W, SCREEN_H};
    fillRect(r, full, th.background);

    // Title bar
    fillRect(r, RECT_HEADER, th.header);
    renderTextCentered(r, fntBig, "Select Theme", RECT_HEADER, th.textPrimary);

    // List panel  600×500  centred on screen
    const SDL_Rect panel = {340, 100, 600, 500};
    fillRect(r, panel, th.panelPlayer);
    outlineRect(r, panel, th.accent);

    // Entries: index 0 = "Default (built-in)",  1..N = theme folder names
    constexpr int ENTRY_H = 48;
    constexpr int ENTRY_X = 350;
    constexpr int ENTRY_Y = 110;
    constexpr int ENTRY_W = 580;

    int totalEntries = 1 + (int)s.themes.names.size();

    for (int i = 0; i < totalEntries && i < 10; ++i) {
        int y = ENTRY_Y + i * ENTRY_H;
        const SDL_Rect row = {ENTRY_X, y, ENTRY_W, ENTRY_H - 2};
        if (i == s.themes.selected) fillRect(r,   row, th.selectedRow);
        else                         outlineRect(r, row, th.btnNormal);
        std::string label = (i == 0) ? "Default (built-in)" : s.themes.names[i - 1];
        int ty = y + (ENTRY_H - TTF_FontHeight(fntMed)) / 2;
        renderText(r, fntMed, label, ENTRY_X + 12, ty, th.textPrimary, ENTRY_W - 24);
    }

    // Footer hint
    fillRect(r, RECT_FOOTER, th.footer);
    renderTextCentered(r, fntSmall, "A Apply  B Back", RECT_FOOTER, th.textHint);
}

// render exit confirmation dialog
static void renderExitConfirmation(SDL_Renderer* r, TTF_Font* fntMed, TTF_Font* fntSmall, const Theme& th) {
    // 1. Dibujar un fondo semitransparente que oscurezca la app por detrás
    SDL_Rect overlay = {0, 0, SCREEN_W, SCREEN_H};
    SDL_SetRenderDrawColor(r, 0, 0, 0, 180); // Negro con alpha
    SDL_RenderFillRect(r, &overlay);

    // 2. Centrar la tarjeta de diálogo (480x240)
    SDL_Rect modal = { (SCREEN_W - 480) / 2, (SCREEN_H - 240) / 2, 480, 240 };
    fillRect(r, modal, th.panelPlayer);
    outlineRect(r, modal, th.accent);

    // 3. Textos de advertencia
    SDL_Rect txtBounds = { modal.x, modal.y + 40, modal.w, 40 };
    renderTextCentered(r, fntMed, "¿Deseas salir de MPlayer?", txtBounds, th.textPrimary);

    SDL_Rect hintBounds = { modal.x, modal.y + 140, modal.w, 40 };
    renderTextCentered(r, fntSmall, "A Confirmar  |  B Cancelar", hintBounds, th.textSecondary);
}

// Theme selected persist
static void guardarConfiguracion(const std::string& themeName) {
    // Asegurar que el directorio existe antes de escribir
    mkdir("sdmc:/switch", 0777);
    mkdir("sdmc:/switch/mp3player", 0777);

    std::ofstream f("sdmc:/switch/mp3player/config.txt");
    if (f.is_open()) {
        f << themeName;
        f.close();
    }
}

static std::string cargarConfiguracion() {
    std::ifstream f("sdmc:/switch/mp3player/config.txt");
    if (f.is_open()) {
        std::string themeName;
        std::getline(f, themeName);
        f.close();
        return themeName;
    }
    return "Default"; // Fallback si no existe el archivo
}

// ─── Entry point ─────────────────────────────────────────────────────────────

int main(int /*argc*/, char* /*argv*/[]) {

    romfsInit();

    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICK);
    IMG_Init(IMG_INIT_PNG | IMG_INIT_JPG);
    TTF_Init();
    Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 4096);
    Mix_AllocateChannels(16);

    SDL_Window* window = SDL_CreateWindow(
        "MP3 Player",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        SCREEN_W, SCREEN_H, SDL_WINDOW_SHOWN);
    SDL_Renderer* renderer = SDL_CreateRenderer(
        window, -1,
        SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

    padConfigureInput(1, HidNpadStyleSet_NpadStandard);
    PadState pad;
    padInitializeDefault(&pad);

    // Load fonts — bundled in romfs:/fonts/font.ttf
    TTF_Font* fntBig   = TTF_OpenFont("romfs:/fonts/font.ttf", 28);
    TTF_Font* fntMed   = TTF_OpenFont("romfs:/fonts/font.ttf", 22);
    TTF_Font* fntSmall = TTF_OpenFont("romfs:/fonts/font.ttf", 18);
    // Fallback: if font fails to load, text won't render but app won't crash

    // Discover themes on romfs
    AppState state;
    state.themes.scan();

    // Load the first found theme automatically; fall back to built-in defaults
    Theme theme;
    std::string temaGuardado = cargarConfiguracion();
    
    if (temaGuardado == "Default" || state.themes.names.empty()) {
        theme = Theme{}; // Cargar valores por defecto
        state.themes.selected = 0;
    } else {
        // Buscar el índice del tema guardado en el catálogo escaneado
        auto it = std::find(state.themes.names.begin(), state.themes.names.end(), temaGuardado);
        if (it != state.themes.names.end()) {
            int idx = std::distance(state.themes.names.begin(), it);
            std::string dir = std::string(THEMES_DIR) + "/" + state.themes.names[idx];
            theme = loadTheme(renderer, dir, state.themes.names[idx]);
            state.themes.selected = idx + 1; // +1 porque el 0 es el "Default"
        } else {
            // Si el tema guardado ya no existe en la SD/RomFS, usar el primero disponible
            std::string dir = std::string(THEMES_DIR) + "/" + state.themes.names[0];
            theme = loadTheme(renderer, dir, state.themes.names[0]);
            state.themes.selected = 1;
        }
    }

    scanMusicDir(state);

    appletSetMediaPlaybackState(true);

    bool running = true;
    while (running && appletMainLoop()) {

        padUpdate(&pad);
        u64 kDown = padGetButtonsDown(&pad);

        if (kDown & HidNpadButton_Plus) {
            if (state.screen != Screen::ExitConfirmation) {
                state.prevScreen = state.screen; // Guardar dónde estábamos
                state.screen = Screen::ExitConfirmation;
            }
        }

        if (state.screen == Screen::Player) {

            if (kDown & HidNpadButton_Y) state.screen = Screen::ThemeSelector;

            if (!state.playlist.empty()) {
                if (kDown & HidNpadButton_AnyDown) {
                    state.selectedIndex = std::min(state.selectedIndex + 1, (int)state.playlist.size() - 1);
                    clampScroll(state);
                }
                if (kDown & HidNpadButton_AnyUp) {
                    state.selectedIndex = std::max(state.selectedIndex - 1, 0);
                    clampScroll(state);
                }
                if (kDown & HidNpadButton_A) playTrack(state, renderer, state.selectedIndex);
                if (kDown & HidNpadButton_B) togglePause(state);
                if (kDown & HidNpadButton_ZL) {
                    int p = state.playingIndex - 1;
                    if (p >= 0) { state.selectedIndex = p; clampScroll(state); playTrack(state, renderer, p); }
                }
                if (kDown & HidNpadButton_ZR) {
                    int n = state.playingIndex + 1;
                    if (n < (int)state.playlist.size()) { state.selectedIndex = n; clampScroll(state); playTrack(state, renderer, n); }
                    else if (state.isLooping && n == (int)state.playlist.size()) { state.selectedIndex = 0; clampScroll(state); playTrack(state, renderer, 0); }
                }
                //activate or deactivate loop when user press R button
                if (kDown & HidNpadButton_R) {
                    toggleLoop(state);
                }
            }

            // Auto-advance and restart if looping enabled
            if (state.isPlaying && !Mix_PlayingMusic()) {
                int n = state.playingIndex + 1;
                if (n < (int)state.playlist.size()) {
                    state.selectedIndex = n; clampScroll(state); playTrack(state, renderer, n);
                } else if (state.isLooping) {
                    state.selectedIndex = 0; clampScroll(state); playTrack(state, renderer, 0);
                } else {
                    state.isPlaying = false;
                }
            }

        } else if (state.screen == Screen::ThemeSelector) {


            int total = 1 + (int)state.themes.names.size();
            if (kDown & HidNpadButton_AnyDown)
                state.themes.selected = std::min(state.themes.selected + 1, total - 1);
            if (kDown & HidNpadButton_AnyUp)
                state.themes.selected = std::max(state.themes.selected - 1, 0);

            if (kDown & HidNpadButton_A) {
                theme.destroy();
                if (state.themes.selected == 0) {
                    theme = Theme{};  // built-in defaults
                    guardarConfiguracion("Default"); // <-- GUARDAR
                } else {
                    int i = state.themes.selected - 1;
                    std::string dir = std::string(THEMES_DIR) + "/" + state.themes.names[i];
                    theme = loadTheme(renderer, dir, state.themes.names[i]);
                    guardarConfiguracion(state.themes.names[i]); // <-- GUARDAR
                }
                state.screen = Screen::Player;
            }

            if (kDown & HidNpadButton_B) state.screen = Screen::Player;

        }else if (state.screen == Screen::ExitConfirmation) {

            if (kDown & HidNpadButton_A) {
                running = false; // Salir del bucle principal
            }

            if (kDown & HidNpadButton_B) {
                state.screen = state.prevScreen; // Volver a la pantalla anterior
            }
        }

        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_RenderClear(renderer);

        if (state.screen == Screen::Player) {
            renderPlayer(renderer, fntBig, fntMed, fntSmall, state, theme);
        } else if (state.screen == Screen::ThemeSelector) {
            renderThemeSelector(renderer, fntBig, fntMed, fntSmall, state, theme);
        } else if (state.screen == Screen::ExitConfirmation) {
            // Dibujamos la pantalla previa abajo para que se vea translúcido por detrás
            if (state.prevScreen == Screen::Player)
                renderPlayer(renderer, fntBig, fntMed, fntSmall, state, theme);
            else
                renderThemeSelector(renderer, fntBig, fntMed, fntSmall, state, theme);
                
            // Pintamos el modal encima de todo
            renderExitConfirmation(renderer, fntMed, fntSmall, theme);
        }

        SDL_RenderPresent(renderer);
    }

    // ── Cleanup — ORDER MATTERS on real hardware ──────────────────────────
    // 1. Stop and free music FIRST — prevents the audio service from hanging.
    //    If this is skipped, the next homebrew app that tries to play audio
    //    will be muted until the console is fully rebooted.
    stopAudio(state);       // calls Mix_HaltMusic + Mix_FreeMusic internally
    Mix_HaltMusic();        // explicit second call: safe no-op if already halted
    Mix_AllocateChannels(0); // release all mixer channels

    appletSetMediaPlaybackState(false);

    // 2. Free GPU textures before destroying the renderer.
    theme.destroy();

    // 3. Close subsystems in reverse-init order.
    Mix_CloseAudio();
    if (fntSmall) TTF_CloseFont(fntSmall);
    if (fntMed)   TTF_CloseFont(fntMed);
    if (fntBig)   TTF_CloseFont(fntBig);
    TTF_Quit();
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    IMG_Quit();
    SDL_Quit();

    // 4. Release romfs last — textures/music may reference paths inside it.
    romfsExit();
    return 0;
}
